/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, PerspectiveCamera } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/bottlenew.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Lid_2.geometry} material={materials['Lid Material']} />
      <mesh geometry={nodes.Bottle_2.geometry} material={materials['Bottle Material']} />
      <PerspectiveCamera makeDefault={false} far={2} near={0} fov={34.52} position={[1.07, 0.3, 0.52]} rotation={[-0.36, 0.75, 0.25]} />
    </group>
  )
}

useGLTF.preload('/bottlenew.gltf')
